name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.6.15", "3.7.15", "3.8.16", "3.9.16", "3.10.9", "3.11.1"]
        django: ["2.2.28", "3.0.14", "3.1.14", "3.2.17", "4.0.9", "4.1.6"]
        exclude:
          - django: "2.2.28"
            python-version: ["3.10.9", "3.11.1"]
          - django: "3.0.14"
            python-version: ["3.10.9", "3.11.1"]
          - django: "3.1.14"
            python-version: ["3.10.9", "3.11.1"]
          - django: "3.2.17"
            python-version: "3.11.1"
          - django: "4.0.9"
            python-version: ["3.6.15", "3.7.15"]
          - django: "4.1.6"
            python-version: ["3.6.15", "3.7.15"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q Django==${{ matrix.django }}
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Run lint
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
