name: tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        django: ["3.2.17", "4.0.9", "4.1.6"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -q Django==${{ matrix.django }}
          pip install -e .
          pip install -r requirements-dev.txt
      - name: Run lint
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
